### ISSUE TITLE
Lost LoanPurpose for Sweden Mortgage applications

### ISSUE THREAD

**Issue by altro3** [open-broker/open-broker-jvm#11]
Field  required for Sweden mortgages too:
```kotlin
    /**
     * Purpose of the loan
     */
    val loanPurpose: LoanPurpose = LoanPurpose.OTHER,
```
But not it exists in Norway PrivateUnsecured loan applications,  Norway Mortgage loan applications, Sweden PrivateUnsecured loan applications and lost in **Sweden Mortgage loan applications**

**Comment by mantono** [comment]
I am not quite sure I am following. Do you mean that _loan purpose_ is present in the specification but not in open-broker-jvm?

I have look quickly into the matter, from what I can tell it is as following

| Domain | Region | In Specification | In open-broker-jvm |
| ----------  | ---------- | --------------------- | -------------------------- | 
| PrivateUnsecuredLoan | Sweden | Yes | Yes |
| PrivateUnsecuredLoan | Norway | Yes | Yes |
| Mortgage | Sweden | No | No |
| Mortgage | Norway | Yes | Yes |

so everything seems to be in order. Have I understood you correctly  @altro3 ?
