### ISSUE TITLE
Change type String to LocalDate for date fields

### ISSUE THREAD

**Issue by altro3** [open-broker/open-broker-jvm#13]
About field (in org.openbroker.no.mortgage.events.Disbursed and org.openbroker.se.mortgage.events.Disbursed classes):
```kotlin
    /**
     *  The date for which the loan was disbursed, formatted
     *  as a ISO-8601 date, in the extended format YYYY-MM-DD
     */
    val date: String
```
You can change String type to LocalDate and say jackson serializing and deserializing this value by ISO-8601 date format. And you don't need validate String format and LocalDate more usefull in developing

**Comment by mantono** [comment]
I think that would be nice if it works, and doesn't break any backwards compatibility (it would still serialize to just "2018-09-14"?).

**Comment by altro3** [comment]
yes, of course. Just add to ObjectMapper this line: ```objectMapper.setDateFormat(StdDateFormat.getDateTimeInstance())```

**Comment by altro3** [comment]
@mantono I can do this and create pull request

**Comment by mantono** [comment]
> @mantono I can do this and create pull request

Sure!
