### ISSUE TITLE
Can we start versioning this library? 

### ISSUE THREAD

**Issue by Torbacka** [open-broker/open-broker-jvm#9]

**Comment by mantono** [comment]
It's a bit tricky really, after all, it contains data for 4 different specifications. Unless we are not interested in semantic versioning and only creating build numbers, in which case it should be quite trivial. What did you have in mind?

**Comment by mantono** [comment]
> Right now its so hard to know how far back your library is when its just a hash.

I understand that and I agree.
>Build numbers would be enough for me and a simple solution.

All right. I will start out with that, for now. Maybe prefixing it with year, or not.

I think in the long run, we might want to consider breaking up this repository into several, per specification. It's a solution that has of course both its pros and cons, and maybe the time for such discussion is not quite now.

**Comment by mantono** [comment]
We are doing it now, in a matter that makes at least a little bit sense. So closing this issue now. Please open it again or create a new issue if you think we should consider versioning this project in a different matter :)
